### ISSUE TITLE
Alchemical Bag Client/Server Sync issue

### ISSUE THREAD

**Issue by Slind14** [sinkillerj/ProjectE#1061]
Version: ProjectE-1.7.10-PE1.9.3h
Modpack: Tekkit Legends
Might be related to: https://github.com/sinkillerj/ProjectE/issues/1058
```
[18:54:08] [Server thread/WARN]: Failed to handle packet for -snip-
net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:464) ~[mw.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:482) ~[nh.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:36) ~[jd.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:101) ~[jd.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.NullPointerException
	at moze_intel.projecte.gameObjs.items.RepairTalisman.updateInAlchBag(RepairTalisman.java:264) ~[RepairTalisman.class:?]
	at moze_intel.projecte.gameObjs.items.AlchemicalBag.func_77663_a(AlchemicalBag.java:95) ~[AlchemicalBag.class:?]
	at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:444) ~[add.class:?]
	at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:386) ~[yx.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:620) ~[yz.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1899) ~[sv.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:315) ~[yz.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:393) ~[mw.class:?]
	... 10 more
```

**Comment by williewillus** [comment]
The talisman somehow ended up not having a nbt tag, not sure how that happened unless it was edited in, idk

I'm probably going to make helpers that wrap around all nbt accesses to check for the tag and autocreate them just to avoid the awkward "make it the first tick" thing that we do right now

**Comment by MaPePeR** [comment]
Auto crafting/condenser feeding into chest. 

Craft repair talisman, instantly drop it on the ground from the crafting window and let the bhb pick it up into a bag.

**Comment by KasBoot** [comment]
Hello,
I was the one having problems with the alchemical bag and the talisman of repair.
I got the alchemical bag probebly transmuted and just put in the bag.
but I''m not 100% sure sorry :(

KasBoot
