### ISSUE TITLE
Unknown error when trying to set custom emc and a few other issues

### ISSUE THREAD

**Issue by revan2811** [sinkillerj/ProjectE#1089]
So first let me say I'm playing MC in german in case some of the problems are localization issues.
I'm using Forge 11.14.3.1543

1. When I try to set a custom EMC for items like rabbit fur, raw mutton or some mod items I get "AN unknown error occurred when attempting to perform this command"

2. Dark Oak Wood doesn't seem to have an EMC value. The planks and all the other woods do have a value.

3. Dark and Red Matter shears can't be used as normal shears (the Katar too but I don't know if that's intended). Right clicking on sheep for example doesn't do anything.

4. Next the Harvest goddess Band when placed on a pedestal (same when held) near mushrooms they grow, alright but to well meaning they replace blocks around them like doors or the pedestal itself. when that happens the band is dropped but the block they replace is lost (actually changed to creative to get that pedestal back).

5. Next is an issue that happens when you are near pedestals with an active dark hole band. the item above the pedestal will be drawn to you by the black hole band but you wont pick it up. It's still connected to the pedestal. To reset that you need to deactivate the band and enter the pedestal inventory take the item out and place it back so it will be displayed correctly again. (Not game-breaking but annoying)

6. The void ring is next on my list I can*t make the Whitelist stick on this one always changes back to blacklist....

7. Not sure if its intended or not but the MK3 Collector needs 1 transparent block above to work despite not needing a light source

8. I wanted to replicate a fully charged Klein Star Omega so put that in an Condenser MK2 . It started collecting the 76365824 EMC needed but only spat out an empty Omega only worth a third of the collected EMC. Don't know if replicating a charged one is actually possible but I thought I would mention it.

Now that was all I have. Sorry for the long list.
But its an awesome mod.

**Comment by sinkillerj** [comment]
1. There should be a error in your log when you attempt to use the command, we will need you to pastebin that log.

4. I have a hard time believing that we would cause a mushroom to overwrite a block space, that sounds like one of the many 1.8 issues that has probably been fixed in 1.8.x but not backported to Forge.

5. Place a chest next to the pedestal.

**Comment by revan2811** [comment]
1. ok here is the error log (was trying to set rabbit hide):

[14:11:06] [Server thread/ERROR]: Couldn't process command: 'projecte setEMC 16'
java.lang.ClassCastException: net.minecraft.util.ResourceLocation cannot be cast to java.lang.String
	at moze_intel.projecte.network.commands.SetEmcCMD.func_71515_b(SetEmcCMD.java:56) ~[SetEmcCMD.class:?]
	at moze_intel.projecte.network.commands.ProjectECMD.func_71515_b(ProjectECMD.java:77) ~[ProjectECMD.class:?]
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:108) [ab.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:85) [ab.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:812) [rj.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:791) [rj.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_180757_a(SourceFile:37) [lu.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [lu.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [ih.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
	at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:714) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:656) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:164) [cyk.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
[14:11:06] [Client thread/INFO]: [CHAT] Bei der Ausführung dieses Befehls trat ein unbekannter Fehler auf

2. don't know if thats the issue the only time i ever saw it was with a Harvest Band so I mentioned it.

3. If you are refering to the black hole issue I meant if I carry the active band around in my inventory or Alchemist bag and walk past an pedestal with a Watch of Flowing Time for example, the watch image will follow me around but is still in the pedestal inventory

**Comment by revan2811** [comment]
I made a test in a creative world just now planted 1 wheat seed placed a pedestal beside that and placed a Harvest band on top... a moment later pedestal gets destroyed  band drops and at the space the pedestal stood a stage 1 wheat  apears and is immediately destroyed because the ground isn't farmland dropping 1 wheat seed and that repeats itself over and over...to me ( and I admit I'm not an expert) that looks like a problem with the Harvest band

**Comment by williewillus** [comment]
@revan2811 what version of ProjectE 1.8 is this? that command unknown error was fixed (I think lol)

**Comment by revan2811** [comment]
I'm using ProjectE-1.8-PE1.1.1.jar so the newest version.

**Comment by SDUBZ** [comment]
im using the newest version too and i cant set emc both single and multiplayer

**Comment by revan2811** [comment]
Thanks for the fixes...now I just need to know how to implement them.
If you can give me a description or a link to one it would be much appreciated.

**Comment by SDUBZ** [comment]
okay what you need screenshots or logs if they show anything retaining to
it?

please reply asap

**Comment by revan2811** [comment]
I downloaded the files williewillus fixed/edited but I have no idear how to implement them into the ProjectE.jar an other way I can think of doing it is editing the files in the jar myself but I don't know how to that either

**Comment by sinkillerj** [comment]
A new build with the changes will be out when I get a chance.
