### ISSUE TITLE
Failure to check against NPE in ConversionProxyImpl.objectToNSS

### ISSUE THREAD

**Issue by rallias** [sinkillerj/ProjectE#1095]
Yeah, I realize this is in part my fault, although you should see null's coming.

java.lang.IllegalArgumentException: Can not turn null () into NormalizedSimpleStack. need ItemStack, FluidStack, String or 'Object'
at moze_intel.projecte.impl.ConversionProxyImpl.objectToNSS(ConversionProxyImpl.java:70)
	at moze_intel.projecte.impl.ConversionProxyImpl.addConversion(ConversionProxyImpl.java:33)
	at xyz.ajp.fluxfyre.util.xmodProjectE.RecipeRegistryProxy.addRecipe(RecipeRegistryProxy.java:20)
	at xyz.ajp.fluxfyre.util.xmodProjectE.RegisterAE2Facade.addItem(RegisterAE2Facade.java:26)
	at xyz.ajp.fluxfyre.util.xmodProjectE.RegisterAE2Facade.initRecipes(RegisterAE2Facade.java:40)
	at xyz.ajp.fluxfyre.FluxFyre.postInit(FluxFyre.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)

**Comment by MaPePeR** [comment]
I think the illegal argument exception is totally valid in that case. It would always be an exception, so it's either an npe or illegal argument.
