### ISSUE TITLE
Missing EMC values from ProjectE items on server, client works fine [ForgeEssentials Issue+Just Enough Calculation?]

### ISSUE THREAD

**Issue by SteelShot** [sinkillerj/ProjectE#1230]
So i have noticed that EMC values are missing from projectE items when i was doing mekanism 5x ore(need the sulfur).
The only exeption to this is that the Philo stone has its EMC value.

I have deleted the projectE config folder, removed minetweaker(could it be the cause?) and rebooted the server. Still the items have no EMC value.

Made a SP world, everything works fine.

I have no clue what could cause this issue, so just ask what you need (logs,cfg etc.) and ill provide anything

P.S 1.7.10 version, latest projectE lates forge server, not using Kcauldron
EDIT 2: Made a new world, still the issue persists
EDIT 3: I have found the cause of this issue:
It is ForgeEssentials, i dont know tho if the issue on your end or theirs, but iam guessing its on theirs end, ill still leave the issue open here, and ill report it in their github aswell.
ForgeEssengtials build 1166

**Comment by sinkillerj** [comment]
Linking for reference ForgeEssentials/ForgeEssentials#2075

**Comment by MaPePeR** [comment]
Cannot reproduce with just ProjectE and `forgeessentials-1.7.10-1.4.4.1146-server` in my dev-instance.

**Comment by SteelShot** [comment]
Yeah, i can not reproduce myself with just those 2, heres the logs and the mods list, tell me which stuff could maybe break PE ill test it out
http://pastebin.com/NNwUiLuQ
https://gist.githubusercontent.com/SteelShot/5edd1fe1acd96d728cc742f926ba5e18/raw/2627e08cfedde101bba28476cfd2de6e635775e2/Log

**Comment by SteelShot** [comment]
I am attacking this issue yet again. This is what i get from the log that would indicate an error or something wrong from 1000+ ProjectE word matches in the log, the error itself says to report it.

http://pastebin.com/raw/yGNpdz40

**Comment by sinkillerj** [comment]
From what I've gathered between the two issues its less a ForgeEssentials issue, and more another mod interacting with ForgeEssentials and ProjectE in a strange way, likely due to a change method. But really the only way to find the exact mod is to set it up with just PE and FE and swap out mods one by one till something breaks. Its not elegant but I'm not seeing anything glaring in the my face atm that could be causing it.

**Comment by SteelShot** [comment]
What would be better FE + and PE and a one another mod,  or FE + PE and keep adding mods together until something breaks? Like i got time its just an extremely dull process..

**Comment by sinkillerj** [comment]
One at a time would be the best in this case, we want as few variables as possible.

**Comment by SteelShot** [comment]
See the reference, i managed to narrow it down to JustEnougCalculation ;)

**Comment by MaPePeR** [comment]
This is probably whats causing it:

```
[14:18:54] [Server thread/FATAL] [ProjectE/ProjectE]: Exception during Mapping Collection from Mapper moze_intel.projecte.emc.mappers.CraftingMapper. PLEASE REPORT THIS! EMC VALUES MIGHT BE INCONSISTENT!
[14:18:54] [Server thread/INFO] [STDERR/ProjectE]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[14:18:54] [Server thread/INFO] [STDERR/ProjectE]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.item.ItemStack.toString(ItemStack.java:371)
[14:18:54] [Server thread/INFO] [STDERR/ProjectE]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.String.valueOf(String.java:2994)
[14:18:54] [Server thread/INFO] [STDERR/ProjectE]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.StringBuilder.append(StringBuilder.java:131)
[14:18:54] [Server thread/INFO] [STDERR/ProjectE]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.AbstractCollection.toString(AbstractCollection.java:462)
[14:18:54] [Server thread/INFO] [STDERR/ProjectE]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at moze_intel.projecte.emc.mappers.CraftingMapper.addMappings(CraftingMapper.java:85)
[14:18:54] [Server thread/INFO] [STDERR/ProjectE]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at moze_intel.projecte.emc.EMCMapper.map(EMCMapper.java:98)
[14:18:54] [Server thread/INFO] [STDERR/ProjectE]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at moze_intel.projecte.PECore.serverStarting(PECore.java:141)
[14:18:54] [Server thread/INFO] [STDERR/ProjectE]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:18:54] [Server thread/INFO] [STDERR/ProjectE]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:18:54] [Server thread/INFO] [STDERR/ProjectE]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:18:54] [Server thread/INFO] [STDERR/ProjectE]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[14:18:54] [Server thread/INFO] [STDERR/ProjectE]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
[14:18:54] [Server thread/INFO] [STDERR/ProjectE]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
[14:18:54] [Server thread/INFO] [STDERR/ProjectE]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:18:54] [Server thread/INFO] [STDERR/ProjectE]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[14:18:54] [Server thread/INFO] [STDERR/ProjectE]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[14:18:54] [Server thread/INFO] [STDERR/ProjectE]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[14:18:54] [Server thread/INFO] [STDERR/ProjectE]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[14:18:54] [Server thread/INFO] [STDERR/ProjectE]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[14:18:54] [Server thread/INFO] [STDERR/ProjectE]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[14:18:54] [Server thread/INFO] [STDERR/ProjectE]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
[14:18:54] [Server thread/INFO] [STDERR/ProjectE]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
[14:18:54] [Server thread/INFO] [STDERR/ProjectE]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:18:54] [Server thread/INFO] [STDERR/ProjectE]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:18:54] [Server thread/INFO] [STDERR/ProjectE]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:18:54] [Server thread/INFO] [STDERR/ProjectE]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[14:18:54] [Server thread/INFO] [STDERR/ProjectE]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[14:18:54] [Server thread/INFO] [STDERR/ProjectE]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[14:18:54] [Server thread/INFO] [STDERR/ProjectE]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[14:18:54] [Server thread/INFO] [STDERR/ProjectE]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[14:18:54] [Server thread/INFO] [STDERR/ProjectE]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[14:18:54] [Server thread/INFO] [STDERR/ProjectE]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
[14:18:54] [Server thread/INFO] [STDERR/ProjectE]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.Loader.serverStarting(Loader.java:789)
[14:18:54] [Server thread/INFO] [STDERR/ProjectE]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:278)
[14:18:54] [Server thread/INFO] [STDERR/ProjectE]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:277)
[14:18:54] [Server thread/INFO] [STDERR/ProjectE]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
[14:18:54] [Server thread/INFO] [STDERR/ProjectE]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

An ItemStack that throws a NPE on toString().

**Comment by SteelShot** [comment]
I am not seeing this error, when reloading the EMC values after removing JEC, it seems the from what i can figure out, JEC and FE interact somehow to cause that NPE?

**Comment by MaPePeR** [comment]
That's really weird :smile: 

As a workaround you can remove one of the mods, so the error does not exist and then enable pregenerated emc in the `mapping.cfg`. Then you will be able to add the mod back and the values should persist. (You will need to delete the file that is generated if you want to change the values again)

**Comment by SteelShot** [comment]
Thats what i used to run for the last 15-ish days :D, i just took that file from the client and slapped into the server. Now i only removed JEC, its not that crucial to loose for a while

**Comment by Towdium** [comment]
My apologies, I just inserted a itemStack with null item into a recipe. That is where the problem occurs. Here is the code I used to use: [https://gist.github.com/Towdium/42f3cc97e4644af0eef8ff759933e5dd](https://gist.github.com/Towdium/42f3cc97e4644af0eef8ff759933e5dd)
