### ISSUE TITLE
1.7.10 is crashing

### ISSUE THREAD

**Issue by TheUglyJames** [sinkillerj/ProjectE#1266]
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 6/13/16 7:01 PM
Description: Initializing game

java.lang.NoClassDefFoundError: bwf
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2575)
	at java.lang.Class.getField0(Class.java:2967)
	at java.lang.Class.getField(Class.java:1693)
	at cpw.mods.fml.client.FMLClientHandler.detectOptifine(FMLClientHandler.java:277)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:192)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: bwf
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 17 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2575)
	at java.lang.Class.getField0(Class.java:2967)
	at java.lang.Class.getField(Class.java:1693)
	at cpw.mods.fml.client.FMLClientHandler.detectOptifine(FMLClientHandler.java:277)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:192)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 122676504 bytes (116 MB) / 198615040 bytes (189 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 10.18.10.4276, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

Whenever i try to start up minecraft using forge it automatically crashes, the report is above.

**Comment by williewillus** [comment]
Mod list

**Comment by TheUglyJames** [comment]
apploed energistics 2
backpacks
biomes o plety
buildcraft
chocolate quest
code chicken core
cofhcore
craftguide
damage indicators
decocraft
extra utilities
industrialcraft
infernal mobs
mam
mantle
NEI
optifine
Pam's harvest craft
reis minimap
tinkers constuct
thaumcraft
thermal dynamics
thermal expansion
thermal foundation
witchery
ProjectE

**Comment by sinkillerj** [comment]
Is this only when ProjectE is introduced? This seams like a install issue rather than one with our mod.

**Comment by TheUglyJames** [comment]
Yea, it was working fine until i added ProjectE

**Comment by williewillus** [comment]
what version of PE

**Comment by williewillus** [comment]
the class it complains about (bwf) does not even exist in 1.7.10. I suspect you are using the 1.9.4 version of ProjectE. please recheck

**Comment by TheUglyJames** [comment]
ok, i will try again, even though it says ProjectE-1.7.10

**Comment by williewillus** [comment]
recheck all your mods, it might not be PE.
I'm 100% sure at least one of your mods is for 1.9.4

**Comment by TheUglyJames** [comment]
i found it thanks for the help
