### ISSUE TITLE
[1.9.4] Harvest Goddess Band try cocoa grows more

### ISSUE THREAD

**Issue by phpr** [sinkillerj/ProjectE#1268]
And minecraft does not like it :(

I just craft a Harvest Goddess Band and got fully grown cocoa not far away.
Now it crash just after loading the world map.

Here is the jstack :

java.lang.IllegalArgumentException: Cannot set property PropertyInteger{name=age, clazz=class java.lang.Integer, values=[0, 1, 2]} to 3 on block minecraft:cocoa, it is not an allowed value
at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:223)

Thread: Server thread
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:223)
	at net.minecraft.block.BlockCocoa.func_176474_b(BlockCocoa.java:173)
	at moze_intel.projecte.utils.WorldHelper.growNearbyRandomly(WorldHelper.java:457)
	at moze_intel.projecte.gameObjs.items.rings.HarvestGoddess.func_77663_a(HarvestGoddess.java:67)
	at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:434)
	at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:340)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:498)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1976)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:227)

Using : 
Minecraft Version: 1.9.4*
Operating System: Linux (amd64) version 4.4.0-24-generic
Java Version: 1.8.0_92, Oracle Corporation
ML: MCP 9.28 Powered by Forge 12.17.0.1957 62 mods loaded, 62 mods active
(...)
UCHIJAAAA	ProjectE{1.9.4-PE1.0.3B} [ProjectE] (ProjectE-1.9.4-PE1.0.3B.jar) 
(...)

Regards,
php

**Comment by williewillus** [comment]
a30770b
