### ISSUE TITLE
Crash when someone use Archangel Smite

### ISSUE THREAD

**Issue by Eufranio** [sinkillerj/ProjectE#1277]
My server crashed when a player used Archangel Smite. 

Main crash:

```
`Time: 29/06/16 22:20
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: javax/vecmath/Tuple3d
	at moze_intel.projecte.gameObjs.items.rings.ArchangelSmite.fireArrow(ArchangelSmite.java:61)
	at moze_intel.projecte.gameObjs.items.rings.ArchangelSmite.func_77659_a(ArchangelSmite.java:54)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:185)
	at net.minecraft.server.management.ItemInWorldManager.func_73085_a(ItemInWorldManager.java:385)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:833)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: javax.vecmath.Tuple3d
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more`
```

Full crash log:
http://pastebin.com/LpV4AwSV

**Comment by sinkillerj** [comment]
#1276 Issue is a missing library on the Thermos side. Unreproducible on a stock Forge server.

**Comment by Mysteryem** [comment]
I'm getting this crash with forge-1.7.10-10.13.4.1614-1.7.10-universal

I ran the forge installer with no problems and then pasted in the mods and config folders for the modpack I was setting up.

This is on a linux server running openjdk java 8, no crash occurs when I load singleplayer on windows 7 with Oracle's java 8.

**Comment by Eufranio** [comment]
Fixed by Thermos.
