### ISSUE TITLE
Crash when using Evertide Amulet in 1.10.2

### ISSUE THREAD

**Issue by PrinceOfAmber** [sinkillerj/ProjectE#1288]
Version: ProjectE-1.9.4-PE1.0.4B.jar

Crash when shooting out a water projectile using Evertide Amulet

Log:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-beta-39.jar)
  AppleCore (AppleCore-mc1.10.2-1.3.5.jar)
  LoadingPlugin (ChunkAnimator-MC1.9.4-1.2.jar)
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 07/07/16 10:00 PM
Description: Ticking entity

java.lang.NoSuchMethodError: net.minecraft.server.management.PlayerInteractionManager.func_73081_b()Lnet/minecraft/world/WorldSettings$GameType;
	at moze_intel.projecte.utils.PlayerHelper.hasBreakPermission(PlayerHelper.java:116)
	at moze_intel.projecte.utils.PlayerHelper.checkedReplaceBlock(PlayerHelper.java:64)
	at moze_intel.projecte.gameObjs.entity.EntityWaterProjectile.func_70071_h_(EntityWaterProjectile.java:55)
	at net.minecraft.world.World.func_72866_a(World.java:1962)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:837)
	at net.minecraft.world.World.func_72870_g(World.java:1932)
	at net.minecraft.world.World.func_72939_s(World.java:1748)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at moze_intel.projecte.utils.PlayerHelper.hasBreakPermission(PlayerHelper.java:116)
	at moze_intel.projecte.utils.PlayerHelper.checkedReplaceBlock(PlayerHelper.java:64)
	at moze_intel.projecte.gameObjs.entity.EntityWaterProjectile.func_70071_h_(EntityWaterProjectile.java:55)
	at net.minecraft.world.World.func_72866_a(World.java:1962)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:837)
	at net.minecraft.world.World.func_72870_g(World.java:1932)

-- Entity being ticked --
Details:
	Entity Type: ProjectE.WaterProjectile (moze_intel.projecte.gameObjs.entity.EntityWaterProjectile)
	Entity ID: 2605355
	Entity Name: entity.ProjectE.WaterProjectile.name
	Entity's Exact location: 1223.78, 4.50, 765.19
	Entity's Block location: World: (1223,4,765), Chunk: (at 7,0,13 in 76,47; contains blocks 1216,0,752 to 1231,255,767), Region: (2,1; contains chunks 64,32 to 95,63, blocks 1024,0,512 to 1535,255,1023)
	Entity's Momentum: 0.41, -0.25, 1.36
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1748)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)

-- Affected level --
Details:
	Level name: C flat testing
	All players: 1 total; [EntityPlayerMP['Lothrazar'/43, l='C flat testing', x=1222.07, y=4.00, z=759.61]]
	Chunk stats: ServerChunkCache: 320 Drop: 0
	Level seed: -6574154556669734031
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (1244,4,788), Chunk: (at 12,0,4 in 77,49; contains blocks 1232,0,784 to 1247,255,799), Region: (2,1; contains chunks 64,32 to 95,63, blocks 1024,0,512 to 1535,255,1023)
	Level time: 347600 game time, 186514 day time

**Comment by williewillus** [comment]
Should be fixed next build
