### ISSUE TITLE
RM/DM Tools

### ISSUE THREAD

**Issue by Chinthor** [sinkillerj/ProjectE#1292]
I'm not getting the crashes that others are getting. My tools just don't do anything. I can "power up" the tools, but can't depower them. Mining any block appears to destroy it, no drop, and leaves a ghost you can get stuck in. Updating the block returns it to what it was before. Right clicking a vein of coal ore gives this error in the launcher log:

[10:43:01] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.server.management.PlayerInteractionManager.func_73081_b()Lnet/minecraft/world/WorldSettings$GameType;
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.NoSuchMethodError: net.minecraft.server.management.PlayerInteractionManager.func_73081_b()Lnet/minecraft/world/WorldSettings$GameType;
	at moze_intel.projecte.utils.PlayerHelper.hasBreakPermission(PlayerHelper.java:116) ~[PlayerHelper.class:?]
	at moze_intel.projecte.utils.WorldHelper.harvestVein(WorldHelper.java:546) ~[WorldHelper.class:?]
	at moze_intel.projecte.gameObjs.items.tools.PEToolBase.tryVeinMine(PEToolBase.java:549) ~[PEToolBase.class:?]
	at moze_intel.projecte.gameObjs.items.tools.DarkPick.func_77659_a(DarkPick.java:69) ~[DarkPick.class:?]
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:162) ~[adz.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:365) ~[lv.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:710) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) ~[jk.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) ~[jk.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more

This is in the pack "Fear the Dark" (not to be confused with "Fear of the Dark") latest pack version, plus: Random Things added and Blood Magic, EnderIO/EnderCore, BloodMoon, Resourceful Crops, and Vampirism all updated to latest beta/alpha/bleeding-edge.
Minecraft is at 1.10 and forge is at 12.18.0.2000

**Comment by williewillus** [comment]
should be fixed next build
