### ISSUE TITLE
[1.9.4-PE1.0.4B] Rightclicking tools produce errors.

### ISSUE THREAD

**Issue by SoraHjort** [sinkillerj/ProjectE#1304]
MC: 1.10.2
Forge: 12.18.1.2014

Right clicking with tools such as the Philosopher stone and the Red Morning Star (and other Red and Dark Matter tools for that matter), produce errors, while also not performing the actions they normally do from right clicking. I've included the error messages for the Philosopher Stone and Red Morning Star. The other tools produce similar errors as well.

## Error for right clicking the Philosopher Stone:

`[19:31:32] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.server.management.PlayerInteractionManager.func_73081_b()Lnet/minecraft/world/WorldSettings$GameType;
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.NoSuchMethodError: net.minecraft.server.management.PlayerInteractionManager.func_73081_b()Lnet/minecraft/world/WorldSettings$GameType;
	at moze_intel.projecte.utils.PlayerHelper.hasBreakPermission(PlayerHelper.java:116) ~[PlayerHelper.class:?]
	at moze_intel.projecte.utils.PlayerHelper.checkedReplaceBlock(PlayerHelper.java:64) ~[PlayerHelper.class:?]
	at moze_intel.projecte.gameObjs.items.PhilosophersStone.func_180614_a(PhilosophersStone.java:67) ~[PhilosophersStone.class:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:755) ~[ForgeHooks.class:?]
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:144) ~[adz.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:493) ~[lv.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:679) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[jj.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[jj.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more
`

## Error for right clicking the Red Morning Star:

`[19:32:17] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.server.management.PlayerInteractionManager.func_73081_b()Lnet/minecraft/world/WorldSettings$GameType;
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.NoSuchMethodError: net.minecraft.server.management.PlayerInteractionManager.func_73081_b()Lnet/minecraft/world/WorldSettings$GameType;
	at moze_intel.projecte.utils.PlayerHelper.hasBreakPermission(PlayerHelper.java:116) ~[PlayerHelper.class:?]
	at moze_intel.projecte.gameObjs.items.tools.PEToolBase.digAOE(PEToolBase.java:347) ~[PEToolBase.class:?]
	at moze_intel.projecte.gameObjs.items.tools.RedStar.func_77659_a(RedStar.java:120) ~[RedStar.class:?]
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:162) ~[adz.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:365) ~[lv.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:710) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) ~[jk.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) ~[jk.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more`

**Comment by SoraHjort** [comment]
Out of curiosity, I checked the closed issues, and noticed that someone has already reported it. This was after I had already searched the open issues for this issue. Maybe, not close it _(or close this and reopen a old one)_ so people don't keep reporting it? So that there is a report visible until the issue is fixed?

**Comment by Araeshkigal** [comment]
Similar problem in latest minecraft with Forge 12.18.0.2007

Right click on freeze ring (sorry I cannot recall the name) does nothing. Pressing G *crashes the game AND corrupts the game file*. Hooray for paranoid backups of saves folder!

Crash report for freeze ring.

---- Minecraft Crash Report ----
// You're mean.

Time: 7/19/16 11:10 PM
Description: Ticking player

java.lang.NoSuchMethodError: net.minecraft.server.management.PlayerInteractionManager.func_73081_b()Lnet/minecraft/world/WorldSettings$GameType;
	at moze_intel.projecte.utils.PlayerHelper.hasBreakPermission(PlayerHelper.java:116)
	at moze_intel.projecte.utils.PlayerHelper.checkedReplaceBlock(PlayerHelper.java:64)
	at moze_intel.projecte.utils.WorldHelper.freezeInBoundingBox(WorldHelper.java:213)
	at moze_intel.projecte.gameObjs.items.rings.Zero.func_77663_a(Zero.java:55)
	at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:437)
	at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:344)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:510)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2019)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:212)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at moze_intel.projecte.utils.PlayerHelper.hasBreakPermission(PlayerHelper.java:116)
	at moze_intel.projecte.utils.PlayerHelper.checkedReplaceBlock(PlayerHelper.java:64)
	at moze_intel.projecte.utils.WorldHelper.freezeInBoundingBox(WorldHelper.java:213)
	at moze_intel.projecte.gameObjs.items.rings.Zero.func_77663_a(Zero.java:55)
	at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:437)
	at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:344)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:510)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2019)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 582
	Entity Name: Doloresa
	Entity's Exact location: -122.84, 66.00, 310.06
	Entity's Block location: World: (-123,66,310), Chunk: (at 5,4,6 in -8,19; contains blocks -128,0,304 to -113,255,319), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:212)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@6b9628ea
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 253833944 bytes (242 MB) / 667582464 bytes (636 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.0.2007 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.0.2007-1.10.0.jar) 
	UCHIJAAAA	Forge{12.18.0.2007} [Minecraft Forge] (forge-1.10.2-12.18.0.2007-1.10.0.jar) 
	UCHIJAAAA	ProjectE{1.9.4-PE1.0.4B} [ProjectE] (ProjectE-1.9.4-PE1.0.4B.jar) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Doloresa'/582, l='New World', x=-122.84, y=66.00, z=310.06]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by sinkillerj** [comment]
ProjectE is not 1.10 compatible, wait for a proper release or play in 1.9.
