### ISSUE TITLE
Major errors

### ISSUE THREAD

**Issue by ihadtomakeanaccountforthis** [sinkillerj/ProjectE#1316]
1) Ticking entity crash upon using the vulcanite amulet projectile to dry out water
http://pastebin.com/5gCgxbjj
2) Error when using any item to non-conventionally change the world (ie. world transmutation, right clicking with any tools)(pulled from multimc)
[13:25:34] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_101]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_101]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1045) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException
	at vazkii.botania.common.network.PacketBotaniaEffect$Handler$1.run(PacketBotaniaEffect.java:136) ~[PacketBotaniaEffect$Handler$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_101]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 17 more

**Comment by williewillus** [comment]
1. one issue per ticket please
2. use pastebin for logs 
3. system/mod info.

Closing this for now, open separate tickets for your revised reports

**Comment by williewillus** [comment]
Oh, you're on 1.10.
Don't do that, the 1.9 builds don't work on 1.10 properly
