### ISSUE TITLE
Repair Talisman Crash - 1.10.2

### ISSUE THREAD

**Issue by Peach774** [sinkillerj/ProjectE#1389]
Ticking player

java.lang.NullPointerException: Ticking player
	at moze_intel.projecte.handlers.PlayerTimers.activateRepair(PlayerTimers.java:60)
	at moze_intel.projecte.gameObjs.items.RepairTalisman.func_77663_a(RepairTalisman.java:64)
	at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:441)
	at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:344)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:510)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

**Comment by williewillus** [comment]
what were you doing when this happened?

**Comment by Peach774** [comment]
it was in my inventory, i was in creative mode, nothing in my inventory to repair. I had a philosophers stone. Maybe it is trying to repair that?

**Comment by williewillus** [comment]
13d6547
