### ISSUE TITLE
Unable to do /projecte setEMC

### ISSUE THREAD

**Issue by TheVeyra** [sinkillerj/ProjectE#1418]
When I first started playing I was able to use the command just fine but it stopped working after some time (a day or two). Now this happens when I try to set the EMC of any item.

[22:36:56] [Server thread/WARN]: Couldn't process command: 'projecte setEMC 32'
java.lang.NullPointerException
	at moze_intel.projecte.config.CustomEMCParser.addToFile(CustomEMCParser.java:150) ~[CustomEMCParser.class:?]
	at moze_intel.projecte.network.commands.SetEmcCMD.func_184881_a(SetEmcCMD.java:122) ~[SetEmcCMD.class:?]
	at moze_intel.projecte.network.commands.ProjectECMD.func_184881_a(ProjectECMD.java:83) ~[ProjectECMD.class:?]
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:104) [k.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:83) [k.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:913) [me.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:892) [me.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [im.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [im.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
[22:36:56] [Client thread/INFO]: [CHAT] An unknown error occurred while attempting to perform this command

**Comment by sinkillerj** [comment]
Was there an item in your hand at the time?

**Comment by TheVeyra** [comment]
Yes, I've tested it with several vanilla and modded items

**Comment by williewillus** [comment]
eb9cd63
