### ISSUE TITLE
Unable to set emc value for an item in hand

### ISSUE THREAD

**Issue by nobo784** [sinkillerj/ProjectE#1447]
I've tried entering in it's name as well. 

Log:
[17:17:34] [Server thread/WARN]: Couldn't process command: 'projecte setemc 64'
java.lang.NullPointerException
	at moze_intel.projecte.config.CustomEMCParser.addToFile(CustomEMCParser.java:153) ~[CustomEMCParser.class:?]
	at moze_intel.projecte.network.commands.SetEmcCMD.func_184881_a(SetEmcCMD.java:122) ~[SetEmcCMD.class:?]
	at moze_intel.projecte.network.commands.ProjectECMD.func_184881_a(ProjectECMD.java:83) ~[ProjectECMD.class:?]
	at com.feed_the_beast.ftbu.ranks.CmdOverride.func_184881_a(CmdOverride.java:50) ~[CmdOverride.class:?]
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:104) [k.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:83) [k.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:913) [me.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:892) [me.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [im.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [im.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]

**Comment by sinkillerj** [comment]
Please ensure that you are using the 1.1.1 version released yesterday.

**Comment by nobo784** [comment]
1.1.1b Is the version that I'm using, this is the latest one right?

**Comment by Tencao** [comment]
Could this be linked to #1434 ?

**Comment by nobo784** [comment]
@Tencao  It's possible, how would I go about checking that?

**Comment by Tencao** [comment]
Upload your custom_emc.json to pastebin then link it back here

**Comment by nobo784** [comment]
There wasn't any nulls but would the 0 have the same effect? http://pastebin.com/raw/VemiC7NE

**Comment by Tencao** [comment]
Do all those items exist in the world currently?

**Comment by Tencao** [comment]
I can confirm that this is related to null items. If an item is listed that no longer exists, it causes a null item

**Comment by nobo784** [comment]
Aha! That's what it was! There were a few things on there from mods that weren't installed anymore. Thanks a bunch Tencao
