### ISSUE TITLE
I have no idea how to describe this

### ISSUE THREAD

**Issue by creepersbane** [sinkillerj/ProjectE#1450]
Using ExtraUtils2 and ProjectE, I built an Infinite EMC Generator with a storage system. The entire system was covered with pedestals with Watches of Flowing Time on them. While using the Destruction Wand from ExtraUtils2, I got this (I don't use pastebin or dropbox):

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreXU2 (extrautils2-1.8.9-alpha-0.0.2.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 12/21/16 11:50 AM
Description: Ticking block entity

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class net.minecraft.block.BlockPlanks$EnumType, values=[oak, spruce, birch, jungle]} as it does not exist in BlockState{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:137)
	at net.minecraft.block.BlockOldLeaf.func_176232_d(BlockOldLeaf.java:85)
	at net.minecraft.block.BlockLeaves.getDrops(BlockLeaves.java:285)
	at net.minecraft.block.Block.func_180653_a(Block.java:492)
	at net.minecraft.block.BlockLeaves.func_180653_a(BlockLeaves.java:229)
	at net.minecraft.block.Block.func_176226_b(Block.java:485)
	at net.minecraft.block.BlockLeaves.func_176235_d(BlockLeaves.java:213)
	at net.minecraft.block.BlockLeaves.func_180650_b(BlockLeaves.java:193)
	at moze_intel.projecte.gameObjs.items.TimeWatch.speedUpRandomTicks(TimeWatch.java:231)
	at moze_intel.projecte.gameObjs.items.TimeWatch.updateInPedestal(TimeWatch.java:362)
	at moze_intel.projecte.gameObjs.tiles.DMPedestalTile.func_73660_a(DMPedestalTile.java:63)
	at net.minecraft.world.World.func_72939_s(World.java:1716)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:544)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:137)
	at net.minecraft.block.BlockOldLeaf.func_176232_d(BlockOldLeaf.java:85)
	at net.minecraft.block.BlockLeaves.getDrops(BlockLeaves.java:285)
	at net.minecraft.block.Block.func_180653_a(Block.java:492)
	at net.minecraft.block.BlockLeaves.func_180653_a(BlockLeaves.java:229)
	at net.minecraft.block.Block.func_176226_b(Block.java:485)
	at net.minecraft.block.BlockLeaves.func_176235_d(BlockLeaves.java:213)
	at net.minecraft.block.BlockLeaves.func_180650_b(BlockLeaves.java:193)
	at moze_intel.projecte.gameObjs.items.TimeWatch.speedUpRandomTicks(TimeWatch.java:231)
	at moze_intel.projecte.gameObjs.items.TimeWatch.updateInPedestal(TimeWatch.java:362)
	at moze_intel.projecte.gameObjs.tiles.DMPedestalTile.func_73660_a(DMPedestalTile.java:63)

-- Block entity being ticked --
Details:
	Name: DMPedestalTile // moze_intel.projecte.gameObjs.tiles.DMPedestalTile
	Block type: ID #200 (tile.pe_dmPedestal // moze_intel.projecte.gameObjs.blocks.Pedestal)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (21,68,245), Chunk: (at 5,4,5 in 1,15; contains blocks 16,0,240 to 31,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #200 (tile.pe_dmPedestal // moze_intel.projecte.gameObjs.blocks.Pedestal)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1716)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:544)

-- Affected level --
Details:
	Level name: Infinite EMC
	All players: 1 total; [EntityPlayerMP['_creepersbane'/5, l='Infinite EMC', x=25.30, y=70.00, z=246.91]]
	Chunk stats: ServerChunkCache: 1174 Drop: 0
	Level seed: 3806181642440437112
	Level generator: ID 02 - largeBiomes, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: 40.00,64.00,252.00 - World: (40,64,252), Chunk: (at 8,4,12 in 2,15; contains blocks 32,0,240 to 47,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 212276 game time, 190561 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 113853 (now: false), thunder time: 134445 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Mac OS X (x86_64) version 10.9.5
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 298922856 bytes (285 MB) / 801841152 bytes (764 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.19 Powered by Forge 11.15.1.1722 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1722.jar) 
	UCHIJAAAA	Forge{11.15.1.1722} [Minecraft Forge] (forge-1.8.9-11.15.1.1722.jar) 
	UCHIJAAAA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.8.9-alpha-0.0.2.jar) 
	UCHIJAAAA	lucky{7.0.2} [Lucky Block] (LuckyBlock_1-8-9_v7-0-2.zip) 
	UCHIJAAAA	ProjectE{1.8.9-PE1.1.4} [ProjectE] (ProjectE-1.8.9-PE1.1.4.jar) 
	Loaded coremods (and transformers): 
CoreXU2 (extrautils2-1.8.9-alpha-0.0.2.jar)
  com.rwtema.extrautils2.asm.ClassTransformerHandler
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['_creepersbane'/5, l='Infinite EMC', x=25.30, y=70.00, z=246.91]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

-------------------------------------------------------------------------------
If you want my world you are more than welcome to have it (lucky block mod not required).

**Comment by williewillus** [comment]
1. 1.8.x version isn't supported anymore
2. "I don't use pastebin" => makes it a PITA for modders to read the report. Please use it :D 
3. this issue is fixed in the 1.10 version

**Comment by creepersbane** [comment]
Thanks
