### ISSUE TITLE
[1.10.2] Null pointer on Repair Talisman updateInAlchChest

### ISSUE THREAD

**Issue by Tencao** [sinkillerj/ProjectE#1467]
Recently I got a null pointer exception on my server with this error:

> java.lang.NullPointerException: Ticking block entity
	at moze_intel.projecte.gameObjs.items.RepairTalisman.updateInAlchChest(RepairTalisman.java:318)
	at moze_intel.projecte.gameObjs.tiles.AlchChestTile.func_73660_a(AlchChestTile.java:107)
	at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:211)
	at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:1304)
	at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zjl000(WorldServer.java:1291)
	at net.minecraft.world.World.func_72939_s(World.java:1282)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:713)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

Which looking at the code, points to this part 
https://github.com/sinkillerj/ProjectE/blob/master/src/main/java/moze_intel/projecte/gameObjs/items/RepairTalisman.java#L223

While i have a few guesses as to why the tile suddenly ends up null, I do know the most simple fix is to simply add a null check after

> AlchChestTile tile = ((AlchChestTile) world.getTileEntity(pos));

**Comment by williewillus** [comment]
2b682092
