### ISSUE TITLE
1.12 issue

### ISSUE THREAD

**Issue by MadRatSRP** [sinkillerj/ProjectE#1555]
java.lang.NoSuchMethodError: net.minecraftforge.fml.relauncher.ReflectionHelper.findMethod(Ljava/lang/Class;Ljava/lang/Object;[Ljava/lang/String;[Ljava/lang/Class;)Ljava/lang/reflect/Method;
	at moze_intel.projecte.utils.ReflectionHelper.<clinit>(ReflectionHelper.java:56)
	at moze_intel.projecte.utils.PlayerHelper.updateScore(PlayerHelper.java:185)
	at moze_intel.projecte.events.PlayerEvents.playerConnect(PlayerEvents.java:101)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_191_PlayerEvents_playerConnect_PlayerLoggedInEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:573)
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:218)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:258)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:74)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:207)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:179)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:784)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Unknown Source)

**Comment by gigaherz** [comment]
I just experienced the same on my 1.12 testing instance. Vanilla launcher, both 1.12 and 1.12.1 crash the same way when entering a world.

**Comment by sinkillerj** [comment]
What forge version are you gents running?

**Comment by BlazingV** [comment]
I'm also experiencing this problem. @sinkillerj I have used 2 forge versions 14.21.1.2428 and 14.21.1.2443 (latest as of now). So I'm guessing it crashes with all/most 1.12 forge versions.

**Comment by gigaherz** [comment]
1.12: 2406
1.12.1: 2446

**Comment by sinkillerj** [comment]
Thanks this helps alot, the build was compiled and tested against 2362. Seams the method must have changed names in the newer builds.

**Comment by gigaherz** [comment]
If you use a version older than the newest recommended, you are doing something wrong. Just saying. ;P

**Comment by sinkillerj** [comment]
With ProjectE we try to retain the drag drop and play compatibility with modpacks, with modpacks the player may not be able to easily update the Forge version in use. This is why older builds are targeted, except in force hand situations like this where we will now have to require users to have the new version.

**Comment by williewillus** [comment]
@gigaherz blame this mod being too easy to update ;p
finished everything before the rb came out. anyways, fixed

**Comment by sinkillerj** [comment]
I have exceptional timing. Fixed build should be out tomorrow.
