### ISSUE TITLE
[1.12] 1.12-PE1.1.0 Error when player disconnect

### ISSUE THREAD

**Issue by Alkasym** [sinkillerj/ProjectE#1598]
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_131]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:391) [nx.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
	at net.minecraft.item.ItemStack.func_77989_b(ItemStack.java:432) ~[ain.class:?]
	at net.minecraftforge.items.ItemStackHandler.setStackInSlot(ItemStackHandler.java:59) ~[ItemStackHandler.class:?]
	at moze_intel.projecte.gameObjs.container.inventory.TransmutationInventory.writeIntoOutputSlot(TransmutationInventory.java:290) ~[TransmutationInventory.class:?]
	at moze_intel.projecte.network.packets.SearchUpdatePKT$Handler$1.run(SearchUpdatePKT.java:49) ~[SearchUpdatePKT$Handler$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_131]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more

**Comment by TomTheHero** [comment]
This still exists in the newest version

**Comment by pupnewfster** [comment]
Unable to reproduce in 1.15
