### ISSUE TITLE
1.12.2 Mercurial Eye Does not Work

### ISSUE THREAD

**Issue by Baythan** [sinkillerj/ProjectE#1958]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): ProjectE-1.12.2-PE1.4.1

Exact Forge version:forge-1.12.2-14.23.5.2847

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): https://paste.ee/p/09ifA

Steps to reproduce:

1. Create Mercurial Eye
2. Load Mercurial Eye with filled Klein Star and block
3. Attempt to activate any mode other than Transmutation (Transmutation works)

What I expected to happen: Creation of blocks

What happened instead: Nothing but spammed error messages in log

**Comment by pupnewfster** [comment]
I am unable to reproduce this in 1.15, and the crash log seems to have expired.

**Comment by Eldresh** [comment]
I can confirm this, also on 1.12.2, ProjectE version 1.4.1. The error message that gets spammed is below.

`01:37:09.588
game
[01:37:09] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
01:37:09.588
game
java.util.concurrent.ExecutionException: java.lang.IllegalAccessError: tried to access field net.minecraft.block.Block.field_149782_v from class moze_intel.projecte.gameObjs.items.MercurialEye
01:37:09.588
game
at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_51]
01:37:09.588
game
at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_51]
01:37:09.588
game
at net.minecraft.util.Util.func_181617_a(Util.java:48) [h.class:?]
01:37:09.588
game
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
01:37:09.588
game
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
01:37:09.588
game
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279) [chd.class:?]
01:37:09.588
game
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
01:37:09.588
game
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
01:37:09.588
game
Caused by: java.lang.IllegalAccessError: tried to access field net.minecraft.block.Block.field_149782_v from class moze_intel.projecte.gameObjs.items.MercurialEye
01:37:09.588
game
at moze_intel.projecte.gameObjs.items.MercurialEye.doBlockPlace(MercurialEye.java:325) ~[MercurialEye.class:?]
01:37:09.588
game
at moze_intel.projecte.gameObjs.items.MercurialEye.fillGaps(MercurialEye.java:366) ~[MercurialEye.class:?]
01:37:09.588
game
at moze_intel.projecte.gameObjs.items.MercurialEye.formBlocks(MercurialEye.java:207) ~[MercurialEye.class:?]
01:37:09.588
game
at moze_intel.projecte.gameObjs.items.MercurialEye.func_180614_a(MercurialEye.java:113) ~[MercurialEye.class:?]
01:37:09.588
game
at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:889) ~[ForgeHooks.class:?]
01:37:09.588
game
at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:186) ~[aip.class:?]
01:37:09.588
game
at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:492) ~[or.class:?]
01:37:09.588
game
at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:741) ~[pa.class:?]
01:37:09.588
game
at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
01:37:09.588
game
at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
01:37:09.588
game
at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:22) ~[hv$1.class:?]
01:37:09.588
game
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_51]
01:37:09.588
game
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]
01:37:09.588
game
at net.minecraft.util.Util.func_181617_a(Util.java:47) ~[h.class:?]
01:37:09.588
game
... 5 more`

**Comment by ShadwDrgn** [comment]
I assume that 1.12.2 is now unsupported. If not it's worth mentionin i have this issue too.

**Comment by ShadwDrgn** [comment]
I believe the culprit here may be https://github.com/sinkillerj/ProjectE/blob/394305d6797f82ba8f502ffd473aefde064928d9/src/main/java/moze_intel/projecte/gameObjs/items/MercurialEye.java#L325
blackHardness is protected (I think) and there'a getter called getBlockHardness
I can't test to be certain because I don't have a dev environment anywhere and haven't been in the modding scene for years, but if you were to update the  1.12.2  package to fix this i'd be super grateful!! :D <3

**Comment by ShadwDrgn** [comment]
I've submit the above PR to fix this. You'll obviously have to update your build version and so on. :)

**Comment by ShadwDrgn** [comment]
I've fixed this twice now. New PR here:
https://github.com/sinkillerj/ProjectE/pull/2222
