### ISSUE TITLE
Minecraft crash issue after using Alchemical Tome and using NEI in Transmutation Tablet

### ISSUE THREAD

**Issue by cluckinator** [sinkillerj/ProjectE#331]
Since I created and consumed the Alchemical Tome, I cannot use NEI to perform searches in the Transmutation Tablet as it crashes Minecraft with a NullPointerException. I was able to use the NEI search in the Transmutation Tablet before I consumed the Alchemical Tablet.

It is fairly likely that another mod has a custom crafting recipe that is messing it up, but I am unable to determine what is happening and it may be helpful to you to know how other mods are interacting. I have uploaded the full crash log to Pastebin here http://pastebin.com/VLCxzpxE in case it is useful.

Description: Ticking screen

Java.lang.NullPointerException: Ticking screen

        at moze_intel.projecte.gameObjs.container.inventory.TransmuteTabletInventory.updateOutputs(TransmuteTabletInventory.java:185)
        at moze_intel.projecte.gameObjs.gui.GUITransmuteTablet.func_73876_c(GUITransmuteTablet.java:78)
        at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1650)
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
        at net.minecraft.client.main.Main.main(SourceFile:148)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:

---------------------------------------------------------------------------------------

-- Head --

Stacktrace:

        at moze_intel.projecte.gameObjs.container.inventory.TransmuteTabletInventory.updateOutputs(TransmuteTabletInventory.java:185)
        at moze_intel.projecte.gameObjs.gui.GUITransmuteTablet.func_73876_c(GUITransmuteTablet.java:78)

-- Affected screen --

Details:

        Screen name: moze_intel.projecte.gameObjs.gui.GUITransmuteTablet

**Comment by Esriel123** [comment]
I can only confirm this. My Crash log:

http://pastebin.com/meCYFs8D

**Comment by MaPePeR** [comment]
So this is probably caused by something reporting `null` for `getDisplayName`  [here](https://github.com/sinkillerj/ProjectE/blob/661950c509b682c49c7825599d201c0146e54cda/src/main/java/moze_intel/projecte/gameObjs/container/inventory/TransmuteTabletInventory.java#L185)

It would be interesting to know, what causes this

**Comment by Kolatra** [comment]
Can anyone confirm or deny whether this still happens?
