### ISSUE TITLE
Ticking Player Crash - v2.13 Alch Bags

### ISSUE THREAD

**Issue by DigitalLunacy** [sinkillerj/ProjectE#372]
[22:46:30] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) ~[nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) ~[bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
Caused by: java.lang.NullPointerException
	at moze_intel.projecte.playerData.AlchemicalBags.get(AlchemicalBags.java:27) ~[AlchemicalBags.class:?]
	at moze_intel.projecte.gameObjs.items.AlchemicalBag.func_77663_a(AlchemicalBag.java:65) ~[AlchemicalBag.class:?]
	at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:381) ~[add.class:?]
	at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:311) ~[yx.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:538) ~[yz.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611) ~[sv.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288) ~[yz.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295) ~[mw.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303) ~[nh.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137) ~[jd.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:8) ~[jd.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) ~[nc.class:?]
	... 5 more
[22:46:30] [Server thread/ERROR]: This crash report has been saved to: E:

**Comment by DigitalLunacy** [comment]
wanted to post i found this was a bug with "better furnaces" its was with a ore double upgrade which i guess was crashing because it was being repaired with the repair tally.

**Comment by Kolatra** [comment]
This should be fixed by the Talisman checking for canRepair().
