### ISSUE TITLE
Server crash with entity arrow

### ISSUE THREAD

**Issue by LemADEC** [sinkillerj/ProjectE#408]
Looks like an obfuscation issue causing crashes with arrows entities:
using dev13

```
---- Minecraft Crash Report ----
// You're mean.

Time: 1/21/15 6:59 PM
Description: Ticking entity

java.lang.NoSuchMethodError: moze_intel.projecte.gameObjs.entity.EntityHomingArrow.func_70016_h(DDD)V
	at moze_intel.projecte.gameObjs.entity.EntityHomingArrow.func_70071_h_(EntityHomingArrow.java:47)
	at net.minecraft.world.World.func_72866_a(World.java:2647)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
	at net.minecraft.world.World.func_72870_g(World.java:2600)
	at net.minecraft.world.World.func_72939_s(World.java:2412)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at moze_intel.projecte.gameObjs.entity.EntityHomingArrow.func_70071_h_(EntityHomingArrow.java:47)
	at net.minecraft.world.World.func_72866_a(World.java:2647)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
	at net.minecraft.world.World.func_72870_g(World.java:2600)

-- Entity being ticked --
Details:
	Entity Type: ProjectE.Homing Arrow (moze_intel.projecte.gameObjs.entity.EntityHomingArrow)
	Entity ID: 461
	Entity Name: entity.ProjectE.Homing Arrow.name
	Entity's Exact location: 860.13, 74.39, 325.35
	Entity's Block location: World: (860,74,325), Chunk: (at 12,4,5 in 53,20; contains blocks 848,0,320 to 863,255,335), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Entity's Momentum: 1.74, 0.24, -0.95
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:2412)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)

-- Affected level --
Details:
	Level name: Manapull
	All players: 1 total; [EntityPlayerMP['ClawmanCat'/456, l='Manapull', x=856.92, y=73.00, z=326.10](ClawmanCat at 856.9230456294555,73.0,326.1042438794397)]
	Chunk stats: ServerChunkCache: 432 Drop: 0
	Level seed: 5421912269181044531
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (563,62,325), Chunk: (at 3,3,5 in 35,20; contains blocks 560,0,320 to 575,255,335), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Level time: 29868704 game time, 130614819 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 71476 (now: false), thunder time: 26749 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 2.6.32-504.3.3.el6.x86_64
	Java Version: 1.7.0_71, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3162567856 bytes (3016 MB) / 4080271360 bytes (3891 MB) up to 8160477184 bytes (7782 MB)
	JVM Flags: 20 total; -Xms4G -Xmx8G -XX:PermSize=256m -XX:MaxPermSize=256m -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalPacing -XX:+AggressiveOpts -XX:NewRatio=3 -XX:SurvivorRatio=3 -XX:TargetSurvivorRatio=80 -XX:MaxTenuringThreshold=8 -XX:+UseParNewGC -XX:MaxGCPauseMillis=10 -XX:GCPauseIntervalMillis=50 -XX:MaxGCMinorPauseMillis=7 -XX:+ExplicitGCInvokesConcurrent -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=60 -XX:+BindGCTaskThreadsToCPUs -Xnoclassgc
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 14
	FML: MCP v9.05 FML v7.10.85.1236 Cauldron-MCPC-Plus vgit-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212 (MC: 1.7.10) (API v1.7.10-R0.1-SNAPSHOT) Minecraft Forge 10.13.2.1236 70 mods loaded, 70 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1236} [Forge Mod Loader] (cauldron-1.7.10-1.1236.05.212-server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1236} [Minecraft Forge] (cauldron-1.7.10-1.1236.05.212-server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ivtoolkit{1.0.2} [IvToolkit] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	itemphysic{1.1.2} [ItemPhysic] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MCVanillaTweaks{1.0} [Mariculture - Vanilla Tweaks] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MobiusCore{1.2.3} [MobiusCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NotEnoughItems{1.0.4.83} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.83-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	malisiscore{1.7.10-0.10.3+unknown-b0.git-unknown} [Malisis Core] (malisiscore-1.7.10-0.10.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CoFHCore{1.7.10R3.0.0B9} [CoFH Core] (aa_CoFHCore-[1.7.10]3.0.0B9-71.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Botania{r1.3-150} [Botania] (Botania-r1.3-150.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	boilerplate{3.0.4} [Boilerplate] (aa_boilerplate-1.7.10-3.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Enchiridion{1.1} [Enchiridion] (aa_Enchiridion-1.7.X-1.2b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	k4lib{1.7.10-0.1.18} [K4Lib] (aa_k4lib-1.7.10-0.1.18-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ttCore{MC1.7.10-0.1.0-55} [ttCore] (aa_ttCore-MC1.7.10-0.1.0-55.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	arsmagica2{1.4.0.005} [Ars Magica 2] (AM2-1.4.0.006.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AncientWarfare{2.4.83-beta-MC1.7.10} [Ancient Warfare Core] (ancientwarfare-2.4.83-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AncientWarfareAutomation{2.4.83-beta-MC1.7.10} [Ancient Warfare Automation] (ancientwarfare-2.4.83-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AncientWarfareNEIPlugin{2.4.83-beta-MC1.7.10} [Ancient Warfare NEI Plugin] (ancientwarfare-2.4.83-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AncientWarfareNpc{2.4.83-beta-MC1.7.10} [Ancient Warfare NPCs] (ancientwarfare-2.4.83-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AncientWarfareStructure{2.4.83-beta-MC1.7.10} [Ancient Warfare Structures] (ancientwarfare-2.4.83-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AncientWarfareVehicle{2.4.83-beta-MC1.7.10} [Ancient Warfare Vehicles] (ancientwarfare-2.4.83-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AppleCore{1.0.2} [AppleCore] (AppleCore-mc1.7.10-1.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (ArchimedesShips-1.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	weaponmod{v1.14.3} [Balkon's WeaponMod] (balkons-weaponmod-1.14.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	battlegear2{1.0.6.3} [Mine & Blade Battlegear 2 - Bullseye] (Battlegear2-Bullseye-1.0.6.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	menagerie{1.0} [menagerie] (dark_menagerie-1.7.10-beta-2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	DragonMounts{r41-1.7.10} [Dragon Mounts] (DragonMounts-r41-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	EnderIO{1.7.10-2.2.6.317} [Ender IO] (EnderIO-1.7.10-2.2.6.317.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ExtrabiomesXL{3.16.0} [ExtrabiomesXL] (extrabiomesxl_1.7.10-3.16.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Steamcraft{0.27.3} [Flaxbeard's Steam Power] (Flaxbeard'sSteamPower-1.7.10-0.27.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineTweaker3{3.0.9B} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.9C.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	fluxedcrystals{0.0.4a} [Fluxed-Crystals] (fluxedCrystals-0.0.4a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	HoloInventory{1.8.3.86} [HoloInventory] (HoloInventory-1.7.10-1.8.3.86.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	LLadders{0.5.0} [Luppii's Ladders] (Ladders-0.5.0-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	malisisdoors{1.7.10-1.3.3} [Malisis' Doors] (malisisdoors-1.7.10-1.3.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mariculture{1.0} [Mariculture] (Mariculture-Deluxe-1.7.10-1.2.4a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MariTech{1.0} [Marine Technlogy] (Mariculture-Deluxe-1.7.10-1.2.4a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AS_Minions{1.9.4} [Minions] (Minions-1.7.10-1.9.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MapWriter{2.1.1} [MapWriter] (Opis-1.2.3_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Opis{1.2.3} [Opis] (Opis-1.2.3_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	harvestcraft{1.7.10d} [Pam's HarvestCraft] (Pam'sHarvestCraft-1.7.10f.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	progressiveautomation{1.5.6} [Progressive Automation] (ProgressiveAutomation-1.7.10-1.5.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjectE{1.7.10-0.2d-dev13} [ProjectE] (ProjectE-1.7.10-0.2d-dev13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Railcraft{9.4.0.0} [Railcraft] (Railcraft_1.7.10-9.4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	reccomplex{0.9.3} [Recurrent Complex] (RecurrentComplex-0.9.3Black.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	RefinedRelocation{1.0.7d} [Refined Relocation] (RefinedRelocation-1.7.10-1.0.7d.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	RPGAdvMod{1.0.0} [RPGAdvMod] (RPGAdvMod-1.0.0_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.376.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	StevesCarts{2.0.0.b18} [Steve's Carts 2] (StevesCarts2.0.0.b18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	StevesFactoryManager{A93} [Steve's Factory Manager] (StevesFactoryManagerA93.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	UndergroundBiomes{0.6h} [Underground Biomes Constructs] (UndergroundBiomesConstructs-1.7.2-0.6h13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	universalcoins{1.7.10-1.5.8} [Universal Coins] (UniversalCoins-1.7.10-1.5.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Waila{1.5.8} [Waila] (Waila-1.5.8a_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	WailaHarvestability{1.1.1} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	wailaplugins{MC1.7.10-0.0.1-10} [WAILA Plugins] (WAILAPlugins-MC1.7.10-0.0.1-10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	wildcaves3{0.4.3.6} [Wild Caves 3] (WildCaves3-0.4.3.6(1.7.2).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	yegamolchattels{1.1} [Ye Gamol Chattels] (YeGamolChattels-1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AS_Ruins{14.4} [Ruins Spawning System] (zs_Ruins-1.7.10-14.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMultipart{1.1.1.320} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	McMultipart{1.1.1.320} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MrTJPCoreMod{1.0} [MrTJPCoreMod] (MrTJPCore-1.7.10-1.0.3.5-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMicroblock{1.1.1.320} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 50; [EntityPlayerMP['ClawmanCat'/456, l='Manapull', x=856.92, y=73.00, z=326.10](ClawmanCat at 856.9230456294555,73.0,326.1042438794397)]
	Is Modded: Definitely; Server brand changed to 'cauldron,craftbukkit,mcpc,fml,forge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by Kolatra** [comment]
I can't reproduce this at all. The ring and arrows work fine for me.

**Comment by sinkillerj** [comment]
This is a cauldron issue, you will need to ensure that it is up to date, if the issue persists you will need to report the missing method to them.

**Comment by LemADEC** [comment]
Cauldron team has switched to Sponge powered, we won't get a fix for them anytime soon.
What are our other options?
