### ISSUE TITLE
Transmutation Tablet/Table Crash On Search

### ISSUE THREAD

**Issue by derpalicious** [sinkillerj/ProjectE#459]
I'm experiencing a crash when attempting to search for an item in the transmutation GUI. This occurs every time a search is attempted, and started after burning an Alchemical Tome.

```
[02:38:19] [Client thread/INFO]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2/5/15 2:38 AM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at moze_intel.projecte.gameObjs.container.inventory.TransmuteTabletInventory.updateOutputs(TransmuteTabletInventory.java:185)
	at moze_intel.projecte.gameObjs.gui.GUITransmuteTablet.func_73869_a(GUITransmuteTablet.java:103)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_73869_a(GuiContainer.java)
	at codechicken.nei.guihook.GuiContainerManager.callKeyTyped(GuiContainerManager.java)
	at codechicken.nei.guihook.GuiContainerManager.keyTyped(GuiContainerManager.java:474)
	at codechicken.nei.guihook.GuiContainerManager.handleKeyboardInput(GuiContainerManager.java:464)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146282_l(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:276)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1629)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at moze_intel.projecte.gameObjs.container.inventory.TransmuteTabletInventory.updateOutputs(TransmuteTabletInventory.java:185)
	at moze_intel.projecte.gameObjs.gui.GUITransmuteTablet.func_73869_a(GUITransmuteTablet.java:103)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_73869_a(GuiContainer.java)
	at codechicken.nei.guihook.GuiContainerManager.callKeyTyped(GuiContainerManager.java)
	at codechicken.nei.guihook.GuiContainerManager.keyTyped(GuiContainerManager.java:474)
	at codechicken.nei.guihook.GuiContainerManager.handleKeyboardInput(GuiContainerManager.java:464)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146282_l(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:276)

-- Affected screen --
Details:
	Screen name: moze_intel.projecte.gameObjs.gui.GUITransmuteTablet

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['swageroth'/2195, l='MpServer', x=1564.03, y=71.62, z=-639.14]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (260,64,269), Chunk: (at 4,4,13 in 16,16; contains blocks 256,0,256 to 271,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 12861251 game time, 12901347 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 55 total; [EntityBrainyZombie['Angry Zombie'/2199, l='MpServer', x=1581.38, y=29.00, z=-607.03], EntityCreeper['Creeper'/2200, l='MpServer', x=1531.06, y=79.00, z=-607.63], EntitySkeleton['Skeleton'/2201, l='MpServer', x=1540.44, y=75.00, z=-608.16], EntitySquid['Squid'/2202, l='MpServer', x=1596.53, y=55.91, z=-602.38], EntityCreeper['Creeper'/2203, l='MpServer', x=1605.50, y=19.00, z=-617.50], EntitySheep['Sheep'/2204, l='MpServer', x=1498.06, y=64.00, z=-589.94], EntityCow['Cow'/2205, l='MpServer', x=1505.38, y=74.00, z=-602.53], GCEntityClientPlayerMP['swageroth'/2195, l='MpServer', x=1564.03, y=71.62, z=-639.14], EntityCow['Cow'/2206, l='MpServer', x=1527.75, y=64.00, z=-683.69], EntitySheep['Sheep'/2207, l='MpServer', x=1585.09, y=65.00, z=-680.47], EntityCreeper['Creeper'/2208, l='MpServer', x=1614.44, y=36.00, z=-668.72], EntityCreeper['Creeper'/2210, l='MpServer', x=1582.97, y=38.00, z=-701.53], EntitySlime['Slime'/2211, l='MpServer', x=1627.31, y=12.00, z=-608.31], EntitySkeleton['Skeleton'/2212, l='MpServer', x=1510.50, y=4.00, z=-591.50], EntitySheep['Sheep'/2213, l='MpServer', x=1498.47, y=66.00, z=-597.53], EntityCow['Cow'/2214, l='MpServer', x=1499.72, y=75.00, z=-603.44], EntityCow['Cow'/2219, l='MpServer', x=1511.81, y=64.00, z=-561.75], EntitySheep['Sheep'/2220, l='MpServer', x=1490.06, y=64.00, z=-585.06], EntitySheep['Sheep'/2221, l='MpServer', x=1498.94, y=64.00, z=-582.03], EntityBat['Bat'/2222, l='MpServer', x=1507.88, y=22.00, z=-690.01], EntityBat['Bat'/2223, l='MpServer', x=1507.54, y=23.00, z=-691.39], EntitySkeleton['Skeleton'/2224, l='MpServer', x=1559.41, y=12.00, z=-704.13], EntitySquid['Squid'/2225, l='MpServer', x=1615.94, y=51.91, z=-585.50], EntitySquid['Squid'/2226, l='MpServer', x=1603.38, y=41.38, z=-573.25], EntityZombie['Zombie'/2230, l='MpServer', x=1592.13, y=36.00, z=-712.25], EntityCreeper['Creeper'/2231, l='MpServer', x=1587.25, y=36.00, z=-702.88], EntityZombie['Zombie'/2232, l='MpServer', x=1587.25, y=36.00, z=-705.28], EntityCartChest['entity.MinecartChest.name'/2365, l='MpServer', x=1691.50, y=17.50, z=-749.53], EntityCreeper['Creeper'/2621, l='MpServer', x=1519.50, y=66.00, z=-648.31], EntityBat['Bat'/2238, l='MpServer', x=1497.59, y=13.10, z=-697.69], EntityCreeper['Creeper'/2110, l='MpServer', x=1545.41, y=75.00, z=-617.00], EntitySkeleton['Skeleton'/2239, l='MpServer', x=1490.09, y=26.00, z=-692.47], EntityZombie['Zombie'/191, l='MpServer', x=1570.30, y=62.00, z=-652.70], EntitySkeleton['Skeleton'/2111, l='MpServer', x=1535.91, y=16.00, z=-629.47], EntitySkeleton['Skeleton'/2240, l='MpServer', x=1628.91, y=39.00, z=-572.50], EntitySkeleton['Skeleton'/2112, l='MpServer', x=1559.69, y=12.00, z=-703.31], EntitySkeleton['Skeleton'/2241, l='MpServer', x=1631.25, y=37.00, z=-569.50], EntityZombie['Zombie'/2242, l='MpServer', x=1631.59, y=38.00, z=-572.06], EntityZombie['Zombie'/194, l='MpServer', x=1541.44, y=5.00, z=-664.13], EntityCreeper['Creeper'/195, l='MpServer', x=1547.38, y=5.00, z=-661.97], EntityBat['Bat'/2245, l='MpServer', x=1505.42, y=24.17, z=-694.76], EntityCartChest['entity.MinecartChest.name'/2375, l='MpServer', x=1668.50, y=15.34, z=-778.50], EntityZombie['Zombie'/2248, l='MpServer', x=1643.50, y=22.00, z=-589.50], EntityCartChest['entity.MinecartChest.name'/2377, l='MpServer', x=1703.50, y=11.50, z=-750.50], EntityEnderman['Enderman'/2121, l='MpServer', x=1577.94, y=35.00, z=-686.97], EntitySheep['Sheep'/2122, l='MpServer', x=1583.28, y=65.00, z=-687.47], EntityCreeper['Creeper'/2639, l='MpServer', x=1609.50, y=52.00, z=-679.50], EntityZombie['Zombie'/2649, l='MpServer', x=1521.57, y=67.00, z=-680.63], EntityCow['Cow'/2276, l='MpServer', x=1494.78, y=63.00, z=-707.19], EntitySkeleton['Skeleton'/2151, l='MpServer', x=1594.34, y=31.00, z=-663.06], EntityCreeper['Creeper'/2279, l='MpServer', x=1645.66, y=35.00, z=-562.97], EntitySkeleton['Skeleton'/2280, l='MpServer', x=1637.16, y=38.00, z=-563.63], EntityBat['Bat'/2152, l='MpServer', x=1570.04, y=38.93, z=-644.50], EntityBat['Bat'/2281, l='MpServer', x=1643.25, y=38.10, z=-564.25], EntitySkeleton['Skeleton'/2285, l='MpServer', x=1627.94, y=39.00, z=-558.56]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:908)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by hiimcody1** [comment]
It looks like they just aren't checking if displayName is null before calling a string function on it.

Adding this before the if statement on that line fixed it for me:

```
if(displayName==null) {
    iter.remove();
    continue;
}
```

**Comment by MaPePeR** [comment]
that is true, yes, but the question is: why is it possible, that there is something with `displayName == null`?

**Comment by hiimcody1** [comment]
Likely some sort of broken item that doesn't have displayName set, maybe a 'technical item' of some sort. MFR has some items that register EMC which don't have an actual display name and use the `tile.yadayada` name. Some mod author probably doesn't have it registered correctly.

**Comment by Sailren** [comment]
i had the same issue remember mapaper?

**Comment by Sailren** [comment]
this seems to occur on the hand held transmutation tablet, the stationary one, seems to work with the tome

**Comment by MaPePeR** [comment]
Yes, i remember. We actually had that same issue at least 3 different times posted. It was fixed by the NEI ingetration in dev14, but this was broken with Multiplayer, so we are seeing the same issue again.

**Comment by Sailren** [comment]
weird

**Comment by hiimcody1** [comment]
Doing some more testing in a fresh world and burning a tome, it's just
straight-up being tossed a null itemstack.

I'll poke around and see if I can isolate it to a specific mod.

**Comment by Sailren** [comment]
this seems to work with the stationary tablet, the issue always happens with the hand held one, i did the same steps with the stationary one, which i did with the hand held and only this crahsed to multiplayer menu

**Comment by MSandro** [comment]
I hope this bug is fixed before the next version is released.

**Comment by sinkillerj** [comment]
A fix has already been pushed which should workaround the issue
