### ISSUE TITLE
Transmutation crashing

### ISSUE THREAD

**Issue by rhyssean** [sinkillerj/ProjectE#513]
Not sure why, but when I search something up in the transmuataion table/ tablet's GUI, it always crashes (I'm using current version),and aswellI would like to know if there is a way to delete my transmutation tablet data on a server (because that may fix it in my opinion)

**Comment by Kolatra** [comment]
Can you provide a crash log?

**Comment by rhyssean** [comment]
I am using the DNS pack from ATLauncher (but I have replaced the files to the new project e), so it will not give me a crash log as far as I can see

**Comment by Kolatra** [comment]
You can always find crash reports in the crash-reports folder of whatever modpack you're playing, it would be the latest one.

**Comment by yogurtsauce** [comment]
I can show you mine.
http://pastebin.com/pqqbgKEc

**Comment by Tencao** [comment]
With yours yogurtsauce, it seems like it's a problem with one of mekanisms items, specifically:
 Item Type: mekanism.common.multipart.ItemPartTransmitter
The easy fix for this, is to remove the emc value of this item, which in turn should also remove it from the transmute tablet.

**Comment by yogurtsauce** [comment]
Worked, thanks dude

**Comment by DrakeBD** [comment]
I have a crash report related to the transmute table hope you can help 

---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 2/27/15 9:15 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at moze_intel.projecte.gameObjs.container.inventory.TransmuteTabletInventory.writeToNBT(TransmuteTabletInventory.java:296)
	at moze_intel.projecte.gameObjs.container.inventory.TransmuteTabletInventory.func_70305_f(TransmuteTabletInventory.java:396)
	at moze_intel.projecte.gameObjs.container.TransmuteTabletContainer.func_75134_a(TransmuteTabletContainer.java:132)
	at net.minecraft.entity.player.EntityPlayer.func_70106_y(EntityPlayer.java:1325)
	at net.minecraft.world.World.func_72900_e(World.java:1371)
	at net.minecraft.server.management.ServerConfigurationManager.func_72367_e(ServerConfigurationManager.java:316)
	at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:633)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:154)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by Tencao** [comment]
Submit the full crash report to pastebin

**Comment by DrakeBD** [comment]
Never used pastbin so here is the crashlog from dropbox
https://dl.dropboxusercontent.com/u/38820381/crashlogs/crash-2015-02-27_21.15.39-server.txt

**Comment by de4ek** [comment]
I am on the ResonantRise3 Pack in eternity Excessive. Crashed when i put the Tome in the table. now every time i try to search it crashes. 
http://pastebin.com/zCbTdET9

**Comment by Norrypt** [comment]
Hi. When I open my Transmutation Tablet and look fore some items, it crashes on a specific page. How can I know wich item is crashing my game?

[crash-2017-07-11_10.43.56-client.txt](https://github.com/sinkillerj/ProjectE/files/1138391/crash-2017-07-11_10.43.56-client.txt)

**Comment by Tencao** [comment]
Make a new issue for this, there's no point digging up old issues
