### ISSUE TITLE
Post Refactor SWRG Crash

### ISSUE THREAD

**Issue by sinkillerj** [sinkillerj/ProjectE#655]
Caused by: java.lang.ClassCastException: net.minecraft.client.entity.EntityClientPlayerMP cannot be cast to net.minecraft.entity.player.EntityPlayerMP
at moze_intel.projecte.gameObjs.items.rings.SWRG.onWornTick(SWRG.java:348) ~[SWRG.class:?]
at baubles.common.event.EventHandlerEntity.playerTick(EventHandlerEntity.java:31) ~[EventHandlerEntity.class:?]

**Comment by williewillus** [comment]
Will look at >.< probably just a missing remote check

**Comment by williewillus** [comment]
Resolved in PR, missed readding the side check.
Also made the speed/slow time function show smoother by doing it on the client as well (safe from desyncs)
