### ISSUE TITLE
Cant load the world

### ISSUE THREAD

**Issue by abdullamu** [sinkillerj/ProjectE#740]
when i load my custom modpack everything loads without error but when i enable projectE and try to load the world is send me back to the main screen with this i'll copy part of it because its too big of a log but its related to thaumcraft too somehow 

	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTags(ThaumcraftCraftingManager.java:551) ~[ThaumcraftCraftingManager.class:?]
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.getAspectsFromIngredients(ThaumcraftCraftingManager.java:854) ~[ThaumcraftCraftingManager.class:?]
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromCraftingRecipes(ThaumcraftCraftingManager.java:833) ~[ThaumcraftCraftingManager.class:?]
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromRecipes(ThaumcraftCraftingManager.java:903) ~[ThaumcraftCraftingManager.class:?]
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTags(ThaumcraftCraftingManager.java:551) ~[ThaumcraftCraftingManager.class:?]
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.getAspectsFromIngredients(ThaumcraftCraftingManager.java:854) ~[ThaumcraftCraftingManager.class:?]
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromCraftingRecipes(ThaumcraftCraftingManager.java:833) ~[ThaumcraftCraftingManager.class:?]
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromRecipes(ThaumcraftCraftingManager.java:903) ~[ThaumcraftCraftingManager.class:?]
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTags(ThaumcraftCraftingManager.java:551) ~[ThaumcraftCraftingManager.class:?]

**Comment by sinkillerj** [comment]
Please post the full crash report on pastebin: http://pastebin.com/

Without the full crash we cannot help you.

**Comment by abdullamu** [comment]
i tried it said u exceeded the limit it was that big

**Comment by abdullamu** [comment]
i tried to upload the file 
http://www.filedropper.com/fml-client-latest

**Comment by sinkillerj** [comment]
Your crash appears to be related to MineFactoryReloaded|CompatThaumcraft, ProjectE is not mentioned.

**Comment by abdullamu** [comment]
but when i went to older version of project e everything loaded fine only with the latest update this happened now im running V. 1.4.6 and its working going to 1.4.7 this happen

**Comment by sinkillerj** [comment]
You will need to contact the Minefactory team with the crash log, there is no further help I can provide regarding this issue.

**Comment by Kolatra** [comment]
For further uploading of reports, use gist.github.com. It's easily viewable on the web and has no limit.

**Comment by sinkillerj** [comment]
@Kolatra PasteBin is preferred, gist can be a little clunky. You should also have no issue on pastebin if you upload the crash log, not the full log.

**Comment by abdullamu** [comment]
sorry guys i know its bit of a problem but its not real crush its silent crush so it wont create for it and in my console it doesnt show it all
