### ISSUE TITLE
Error Loading NBT data

### ISSUE THREAD

**Issue by Tencao** [sinkillerj/ProjectE#755]
So I've been running the server for a good few months now, however it's just started to refuse to boot up with this error. Any possible way of fixing this without deleting the entire dat?

[13:54:53] [Server thread/ERROR]: Caught exception from ProjectE
net.minecraft.util.ReportedException: Loading NBT data
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:407) ~[dh.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:52) ~[dh.class:?]
	at net.minecraft.nbt.CompressedStreamTools.func_152455_a(CompressedStreamTools.java:170) ~[du.class:?]
	at net.minecraft.nbt.CompressedStreamTools.func_152456_a(CompressedStreamTools.java:125) ~[du.class:?]
	at net.minecraft.nbt.CompressedStreamTools.func_152458_a(CompressedStreamTools.java:216) ~[du.class:?]
	at net.minecraft.nbt.CompressedStreamTools.func_74797_a(CompressedStreamTools.java:200) ~[du.class:?]
	at moze_intel.projecte.playerData.IOHandler.readData(IOHandler.java:62) ~[IOHandler.class:?]
	at moze_intel.projecte.playerData.IOHandler.init(IOHandler.java:53) ~[IOHandler.class:?]
	at moze_intel.projecte.PECore.serverStarting(PECore.java:151) ~[PECore.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:KCauldron-1.7.10-4.1403.69]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:KCauldron-1.7.10-4.1403.69]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:KCauldron-1.7.10-4.1403.69]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:KCauldron-1.7.10-4.1403.69]
	at cpw.mods.fml.common.Loader.serverStarting(Loader.java:764) [Loader.class:KCauldron-1.7.10-4.1403.69]
	at cpw.mods.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:282) [FMLCommonHandler.class:KCauldron-1.7.10-4.1403.69]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:366) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.io.EOFException
	at java.io.DataInputStream.readUnsignedShort(Unknown Source) ~[?:1.8.0_45]
	at java.io.DataInputStream.readUTF(Unknown Source) ~[?:1.8.0_45]
	at java.io.DataInputStream.readUTF(Unknown Source) ~[?:1.8.0_45]
	at net.minecraft.nbt.NBTTagCompound.func_152448_b(NBTTagCompound.java:388) ~[dh.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:50) ~[dh.class:?]
	at net.minecraft.nbt.NBTTagList.func_152446_a(NBTTagList.java:54) ~[dq.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:398) ~[dh.class:?]
	... 38 more

**Comment by sinkillerj** [comment]
Somehow your PE save has become corrupt, and whatever caused it likely caused some other world corruption as well. You could attempt to open the file with NBTExplorer, and if it is able to read it remove corrupt data and resave, but beyond that I'm not sure how you could recover it. Minecraft can be a bit finky if a server crashes or otherwise is terminated incorrectly, so it is a good idea to take regular backups, there are also backup mods available such as AromaBackup.

**Comment by Tencao** [comment]
Just like to say, this error appears to have happened again, and it's whenever I update a major mod (In this case, buildcraft), I have pasted the error again below, I'm not sure how they compare, but it seems to happen on every major mod update.

http://pastebin.com/Ap8dD8er

It seems to only corrupt the knowledge.dat, not the bags
