### ISSUE TITLE
Invalid armor application

### ISSUE THREAD

**Issue by Tencao** [sinkillerj/ProjectE#773]
Now, I know I reported this here before, and you asked me to tell them to use noRepair, however since they have implemented it, it's still erroring, and now they're pointing me back here, so here's the error.
```
[11:49:25] [Server thread/WARN]: Detected invalid armor damage application:
java.lang.Throwable
at ic2.core.item.armor.ItemArmorElectric.setDamage(ItemArmorElectric.java:150)
[ItemArmorElectric.class:?]
at net.minecraft.item.ItemStack.func_77964_b(ItemStack.java:248) [add.class:?]
at
moze_intel.projecte.gameObjs.items.AlchemicalBag.func_77663_a(AlchemicalBag.java:127)
[AlchemicalBag.class:?]
at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:444) [add.class:?]
at
net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:386)
[yx.class:?]
at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:620)
[yz.class:?]
at
net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1899)
[sv.class:?]
at
net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:315)
[yz.class:?]
at
net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:393)
[mw.class:?]
at
net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:482)
[nh.class:?]
at
net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:36)
[jd.class:?]
at
net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:101)
[jd.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244)
[ej.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
[nc.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991)
[MinecraftServer.class:?]
at
net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
[lt.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
[MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
[MinecraftServer.class:?]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
====================================================================== 
```

**Comment by RAnders00** [comment]
@Tencao Next time you can put three backticks before and after the stacktrace to make it much easier to read, just like this:

    ```
    Stacktrace here
    ```

So it looks like this:
```
[11:49:25] [Server thread/WARN]: Detected invalid armor damage application: java.lang.Throwable
at ic2.core.item.armor.ItemArmorElectric.setDamage(ItemArmorElectric.java:150 [ItemArmorElectric.class:?]
at net.minecraft.item.ItemStack.func_77964_b(ItemStack.java:248) [add.class:?]
and so on...
```

**Comment by Tencao** [comment]
Thanks for that, I've modified the original post to include it
