### ISSUE TITLE
WorldEdit screws up

### ISSUE THREAD

**Issue by abalabahaha** [sinkillerj/ProjectE#776]
Upon using WorldEdit to somehow set a Collector hooked up to an active condensor directly/through Relay to air (//regen, //set, etc.), the server crashes with a NPE.
```
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 05/06/15 13:32
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
        at moze_intel.projecte.gameObjs.tiles.TileEmcProducer.checkSurroundingBlocks(TileEmcProducer.java:71)
        at moze_intel.projecte.gameObjs.tiles.RelayMK1Tile.func_145845_h(RelayMK1Tile.java:52)
        at net.minecraft.world.World.func_72939_s(World.java:2487)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:664)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
        at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
        at moze_intel.projecte.gameObjs.tiles.TileEmcProducer.checkSurroundingBlocks(TileEmcProducer.java:71)
        at moze_intel.projecte.gameObjs.tiles.RelayMK1Tile.func_145845_h(RelayMK1Tile.java:52)

-- Block entity being ticked --
Details:
        Name: RelayMK3Tile // moze_intel.projecte.gameObjs.tiles.RelayMK3Tile
        Block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
        Block data value: 0 / 0x0 / 0b0000
        Block location: World: (-292,66,117), Chunk: (at 12,4,5 in -19,7; contains blocks -304,0,112 to -289,255,127), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
        Actual block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
        Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
        at net.minecraft.world.World.func_72939_s(World.java:2487)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:664)
```

**Comment by sinkillerj** [comment]
WorldEdit does not trigger block updates, this is by its design, there is nothing we can do to resolve this issue. You should never remove one of a linked pair with WorldEdit. If you are unable to get back into your world please try setting remove erroring to true in your forge config.

**Comment by MaPePeR** [comment]
It's a npe in our code... We *could * check for it.

**Comment by sinkillerj** [comment]
@MaPePeR A NPE caused by a target being removed without a block update, there is no legitimate situation where this would happen.

**Comment by MaPePeR** [comment]
Removing [this](https://github.com/sinkillerj/ProjectE/blob/master/src/main/java/moze_intel/projecte/gameObjs/tiles/TileEmcProducer.java#L61) weird way to request the `this`-Object would probably help:

```
TileEmcProducer tile = (TileEmcProducer) worldObj.getTileEntity(xCoord, yCoord, zCoord);
```
