### ISSUE TITLE
ArithmeticException (Different Stack trace than the other ArithmeticException)

### ISSUE THREAD

**Issue by Turkey2349** [sinkillerj/ProjectE#841]
[23:39:12] [Server thread/ERROR] [FML]: Caught exception from ProjectE
java.lang.ArithmeticException: overflow: mul
        at org.apache.commons.lang3.math.Fraction.mulAndCheck(Fraction.java:643) ~[commons-lang3-3.3.2.jar:3.3.2]
        at org.apache.commons.lang3.math.Fraction.multiplyBy(Fraction.java:807) ~[commons-lang3-3.3.2.jar:3.3.2]
        at moze_intel.projecte.emc.arithmetics.HiddenFractionArithmetic.mul(HiddenFractionArithmetic.java:35) ~[HiddenFractionArithmetic.class:?]
        at moze_intel.projecte.emc.arithmetics.HiddenFractionArithmetic.mul(HiddenFractionArithmetic.java:7) ~[HiddenFractionArithmetic.class:?]
        at moze_intel.projecte.emc.SimpleGraphMapper.generateValues(SimpleGraphMapper.java:101) ~[SimpleGraphMapper.class:?]
        at moze_intel.projecte.emc.valuetranslators.FractionToIntegerTranslator.generateValues(FractionToIntegerTranslator.java:21) ~[FractionToIntegerTranslator.class:?]
        at moze_intel.projecte.emc.EMCMapper.map(EMCMapper.java:84) ~[EMCMapper.class:?]
        at moze_intel.projecte.PECore.serverStarting(PECore.java:138) ~[PECore.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_79]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_79]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_79]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_79]
        at  .... and so on

PR 820 did not fix this issue as this stack trace does not have it passing though the changed code. We do know that the error is because of items and blocks that exceed the max integer limit, but this should be caught.

**Comment by Lavaflow** [comment]
I started to get an error similar to this when I tried to add OptiFine to my instance (1.8). I don't remember if it's exactly like this, but there was some stuff about HIddenFractionArithmetic in there.

**Comment by williewillus** [comment]
Optifine shouldnt do anything with that unless they patch apache commons 0.0 (in which case they deserve to burn in the nether). Any other mods you remember adding around that time?

**Comment by MaPePeR** [comment]
I will write some test cases for this and the other one later today. 

Optifine should not cause this in any possible way.

**Comment by MaPePeR** [comment]
Now that this is fixed now i would really like to see a log with the latest ProjectE and the same mods that caused the ArithmeticException to occur.
