### ISSUE TITLE
In MindStone.java, code assumes a nonnull value to be returned by tile.getItemStack()

### ISSUE THREAD

**Issue by grg-n-sox** [sinkillerj/ProjectE#861]
Code in question:
https://github.com/sinkillerj/ProjectE/blob/f8192274bc7f98b57dec640db8f035d84b61f25b/src/main/java/moze_intel/projecte/gameObjs/items/rings/MindStone.java#L194

Issue: Testing has found that in some rare cases, the tile.getItemStack() call can return a null value. When it does so, it ends up causing a NullPointerException over in MindStone.getStoredXP() @ L138. Don't know how to best handle a null in this case. Possibly just treat it like an empty item stack if that's a thing?

Here's the log.

```
java.lang.NullPointerException: Ticking block entity
	at moze_intel.projecte.gameObjs.items.rings.MindStone.getStoredXP(MindStone.java:138)
	at moze_intel.projecte.gameObjs.items.rings.MindStone.canStore(MindStone.java:143)
	at moze_intel.projecte.gameObjs.items.rings.MindStone.suckXP(MindStone.java:202)
	at moze_intel.projecte.gameObjs.items.rings.MindStone.updateInPedestal(MindStone.java:194)
	at moze_intel.projecte.gameObjs.tiles.DMPedestalTile.func_145845_h(DMPedestalTile.java:49)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at moze_intel.projecte.gameObjs.items.rings.MindStone.getStoredXP(MindStone.java:138)
	at moze_intel.projecte.gameObjs.items.rings.MindStone.canStore(MindStone.java:143)
	at moze_intel.projecte.gameObjs.items.rings.MindStone.suckXP(MindStone.java:202)
	at moze_intel.projecte.gameObjs.items.rings.MindStone.updateInPedestal(MindStone.java:194)
	at moze_intel.projecte.gameObjs.tiles.DMPedestalTile.func_145845_h(DMPedestalTile.java:49)

-- Block entity being ticked --
Details:
	Name: DMPedestalTile // moze_intel.projecte.gameObjs.tiles.DMPedestalTile
	Block type: ID #2164 (tile.pe_dmPedestal // moze_intel.projecte.gameObjs.blocks.Pedestal)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (1412,88,1045), Chunk: (at 4,5,5 in 88,65; contains blocks 1408,0,1040 to 1423,255,1055), Region: (2,2; contains chunks 64,64 to 95,95, blocks 1024,0,1024 to 1535,255,1535)
	Actual block type: ID #2164 (tile.pe_dmPedestal // moze_intel.projecte.gameObjs.blocks.Pedestal)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
```

**Comment by williewillus** [comment]
It doesn't make sense because if MindStone's updateInPedestal is being called then there *must* be a mind stone in the pedestal. Only thing I can think of is some client/server race conditions that is causing it to be removed on the client. Investigating.

**Comment by williewillus** [comment]
Are you able to reproduce this reliably?

**Comment by grg-n-sox** [comment]
Sadly no as this occurred on an active server and we ended up having to mcedit the block out to make the server stable again. What I can say is that before having to delete that block, any time the chunk containing the block was loaded, it would crash the server with that same stack trace. I will see if I can ask the person who set up the crashing block in the first place what happened. However, the last time I tried to get details out of him, all he said was "I dunno, I was just fooling around with DM pedestals and on of them crashed on me."

**Comment by williewillus** [comment]
Ah, I managed to reproduce it by trickily getting a mindstone into the pedestal that didn't have an nbt tag, looking at a fix

**Comment by grg-n-sox** [comment]
Thanks for the fix. How did you have to get the mindstone into the pedestal?

**Comment by williewillus** [comment]
Tossed a mindstone out of the creative inventory into a hopper over a pedestal xD
They only get their nbt tags when they get placed into a players inventory, so by not loetting it touch one at all I was able to reproduce it :p
