### ISSUE TITLE
Flan's mod guns can't be transmuted properly

### ISSUE THREAD

**Issue by Viktorsmg** [sinkillerj/ProjectE#932]
I assume similar things might happen with vehicles and other things as well.I set an EMC value for a gun,fed it to the tablet,pulled it out and the resulting gun causes a crash/freeze when put in the gun modification table.

---- Minecraft Crash Report ----
WARNING: coremods are present:
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
BOPLoadingPlugin (BiomesOPlenty-1.8-3.0.0.1389-universal.jar)
CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-universal.jar)
CCCDeobfPlugin (unknown)
NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-universal.jar)
Contact their authors BEFORE contacting forge
// This doesn't make any sense!
Time: 8/16/15 10:49 PM
Description: Updating screen events
java.lang.NullPointerException: Updating screen events
at com.flansmod.common.guns.InventoryGunModTable.func_70296_d(InventoryGunModTable.java:35)
at net.minecraft.inventory.InventoryBasic.func_70299_a(SourceFile:119)
at net.minecraft.inventory.Slot.func_75215_d(Slot.java:68)
at net.minecraft.inventory.Container.func_75144_a(Container.java:306)
at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:492)
at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:506)
at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:638)
at net.minecraft.client.gui.inventory.GuiContainer.public_func_146984_a(GuiContainer.java)
at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17)
at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:455)
at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:607)
at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:558)
at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
at com.flansmod.client.gui.GuiGunModTable.func_146274_d(GuiGunModTable.java:234)
at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517)
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1671)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1029)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
at net.minecraft.client.main.Main.main(SourceFile:120)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Stacktrace:
at com.flansmod.common.guns.InventoryGunModTable.func_70296_d(InventoryGunModTable.java:35)
at net.minecraft.inventory.InventoryBasic.func_70299_a(SourceFile:119)
at net.minecraft.inventory.Slot.func_75215_d(Slot.java:68)
at net.minecraft.inventory.Container.func_75144_a(Container.java:306)
at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:492)
at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:506)
at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:638)
at net.minecraft.client.gui.inventory.GuiContainer.public_func_146984_a(GuiContainer.java)
at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17)
at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:455)
at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:607)
at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:558)
at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
at com.flansmod.client.gui.GuiGunModTable.func_146274_d(GuiGunModTable.java:234)
at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517)
-- Affected screen --
Details:
Screen name: com.flansmod.client.gui.GuiGunModTable
-- Affected level --
Details:
Level name: MpServer
All players: 1 total; [EntityPlayerSP['Viktor_smg'/182, l='MpServer', x=-50.96, y=65.00, z=-34.86]]
Chunk stats: MultiplayerChunkCache: 272, 272
Level seed: 0
Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
Level generator options: 
Level spawn location: -35.00,64.00,-37.00 - World: (-35,64,-37), Chunk: (at 13,4,11 in -3,-3; contains blocks -48,0,-48 to -33,255,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
Level time: 269631 game time, 178170 day time
Level dimension: 0
Level storage version: 0x00000 - Unknown?
Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Forced entities: 56 total; [EntityCreeper['Creeper'/5633, l='MpServer', x=9.50, y=48.00, z=-42.50], EntityCreeper['Creeper'/5634, l='MpServer', x=7.91, y=49.00, z=-40.44], EntitySpider['Spider'/14468, l='MpServer', x=-93.72, y=16.09, z=39.28], EntityBat['Bat'/134, l='MpServer', x=19.75, y=20.10, z=-9.75], EntitySpider['Spider'/14471, l='MpServer', x=-103.09, y=13.00, z=37.22], EntitySkeleton['Skeleton'/21255, l='MpServer', x=-15.56, y=36.00, z=-116.72], EntitySkeleton['Skeleton'/12936, l='MpServer', x=-22.50, y=21.00, z=-10.50], EntityBat['Bat'/16009, l='MpServer', x=-16.13, y=42.13, z=-102.53], EntityCreeper['Creeper'/22922, l='MpServer', x=22.50, y=15.02, z=-42.50], EntityZombie['Zombie'/14475, l='MpServer', x=-101.34, y=13.00, z=38.66], EntitySkeleton['Skeleton'/7318, l='MpServer', x=-109.13, y=11.00, z=10.50], EntityBat['Bat'/7576, l='MpServer', x=-65.69, y=13.10, z=-60.25], EntityZombie['Zombie'/11294, l='MpServer', x=-91.53, y=12.00, z=-86.94], EntityBat['Bat'/18603, l='MpServer', x=4.97, y=50.04, z=-37.86], EntityZombie['Zombie'/5164, l='MpServer', x=15.41, y=17.00, z=-8.53], EntityCreeper['Creeper'/23085, l='MpServer', x=-35.50, y=26.00, z=-82.50], EntityBat['Bat'/18606, l='MpServer', x=-89.73, y=38.91, z=31.41], EntityCreeper['Creeper'/23086, l='MpServer', x=-35.50, y=26.00, z=-85.50], EntityBat['Bat'/18608, l='MpServer', x=-87.70, y=38.74, z=27.97], EntityBat['Bat'/18609, l='MpServer', x=-72.17, y=34.01, z=29.24], EntitySkeleton['Skeleton'/16821, l='MpServer', x=-114.50, y=17.00, z=27.50], EntityPlayerSP['Viktor_smg'/182, l='MpServer', x=-50.96, y=65.00, z=-34.86], EntityBat['Bat'/59, l='MpServer', x=-81.25, y=23.10, z=-28.75], EntityCreeper['Creeper'/8642, l='MpServer', x=-94.50, y=13.00, z=-77.50], EntityZombie['Zombie'/67, l='MpServer', x=-64.50, y=15.00, z=-89.50], EntitySquid['Squid'/20292, l='MpServer', x=10.00, y=61.31, z=-28.47], EntitySquid['Squid'/14533, l='MpServer', x=6.59, y=60.88, z=10.50], EntityZombie['Zombie'/20549, l='MpServer', x=-122.50, y=29.00, z=-19.50], EntitySquid['Squid'/20294, l='MpServer', x=10.97, y=62.22, z=-30.94], EntityZombie['Zombie'/20550, l='MpServer', x=-121.50, y=29.00, z=-16.50], EntitySpider['Spider'/18247, l='MpServer', x=16.97, y=21.70, z=-60.17], EntitySquid['Squid'/20295, l='MpServer', x=12.25, y=61.94, z=-33.56], EntitySkeleton['Skeleton'/20551, l='MpServer', x=-121.50, y=29.00, z=-23.50], EntitySquid['Squid'/14536, l='MpServer', x=8.94, y=58.75, z=-4.56], EntitySkeleton['Skeleton'/20552, l='MpServer', x=-120.50, y=29.00, z=-21.50], EntityZombie['Zombie'/19019, l='MpServer', x=23.50, y=15.00, z=-42.50], EntityZombie['Zombie'/18252, l='MpServer', x=-81.50, y=35.00, z=34.50], EntityBat['Bat'/10190, l='MpServer', x=-90.25, y=25.10, z=-32.63], EntityZombie['Zombie'/10066, l='MpServer', x=-79.66, y=17.00, z=-85.66], EntitySpider['Spider'/19414, l='MpServer', x=-79.63, y=20.00, z=-101.47], EntityZombie['Zombie'/10071, l='MpServer', x=-106.06, y=28.00, z=-19.53], EntitySpider['Spider'/19415, l='MpServer', x=-73.91, y=21.00, z=-93.59], EntityZombie['Zombie'/10072, l='MpServer', x=-106.81, y=24.00, z=-24.28], EntitySkeleton['Skeleton'/10074, l='MpServer', x=-116.09, y=24.00, z=-23.47], EntitySpider['Spider'/13915, l='MpServer', x=-97.72, y=13.00, z=32.69], EntitySkeleton['Skeleton'/13919, l='MpServer', x=-101.47, y=13.02, z=33.13], EntityBat['Bat'/101, l='MpServer', x=0.22, y=30.10, z=-75.56], EntityBat['Bat'/12519, l='MpServer', x=16.55, y=19.89, z=-43.54], EntityCreeper['Creeper'/17768, l='MpServer', x=-9.50, y=42.00, z=-108.50], EntityCreeper['Creeper'/17769, l='MpServer', x=-4.03, y=43.00, z=-103.56], EntityZombie['Zombie'/17770, l='MpServer', x=1.06, y=41.00, z=-109.44], EntityCreeper['Creeper'/18159, l='MpServer', x=-104.41, y=10.00, z=-81.09], EntitySkeleton['Skeleton'/14451, l='MpServer', x=-124.50, y=48.00, z=39.50], EntityCreeper['Creeper'/17783, l='MpServer', x=25.50, y=28.00, z=-34.50], EntitySkeleton['Skeleton'/5624, l='MpServer', x=-46.50, y=20.00, z=-91.50], EntityCreeper['Creeper'/14456, l='MpServer', x=-78.50, y=37.00, z=-23.50]]
Retry entities: 0 total; []
Server brand: fml,forge
Server type: Integrated singleplayer server
Stacktrace:
at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:351)
at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2503)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:366)
at net.minecraft.client.main.Main.main(SourceFile:120)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
-- System Details --
Details:
Minecraft Version: 1.8
Operating System: Windows 8.1 (amd64) version 6.3
Java Version: 1.8.0_31, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 1421568848 bytes (1355 MB) / 2072510464 bytes (1976 MB) up to 2072510464 bytes (1976 MB)
JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048M -Xms2048M
IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 105
FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1502 8 mods loaded, 8 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
UCHIJAAAA mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
UCHIJAAAA FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.3.1502.jar) 
UCHIJAAAA Forge{11.14.3.1502} [Minecraft Forge] (forge-1.8-11.14.3.1502.jar) 
UCHIJAAAA CodeChickenCore{1.0.5.36} [CodeChicken Core] (minecraft.jar) 
UCHIJAAAA NotEnoughItems{1.0.5.104} [Not Enough Items] (NotEnoughItems-1.8-1.0.5.104-universal.jar) 
UCHIJAAAA BiomesOPlenty{3.0.0} [Biomes O' Plenty] (BiomesOPlenty-1.8-3.0.0.1389-universal.jar) 
UCHIJAAAA flansmod{5.0} [Flan's Mod] (Flan's Mod-1.8-5.0.jar) 
UCHIJAAAA ProjectE{1.8-PE1.0.1B} [ProjectE] (ProjectE-1.8-PE1.0.1B.jar) 
Loaded coremods (and transformers): 
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
codechicken.lib.asm.ClassHeirachyManager
codechicken.lib.asm.RenderHookTransformer
BOPLoadingPlugin (BiomesOPlenty-1.8-3.0.0.1389-universal.jar)

CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-universal.jar)
codechicken.core.asm.InterfaceDependancyTransformer
codechicken.core.asm.TweakTransformer
codechicken.core.asm.DelegatedTransformer
codechicken.core.asm.DefaultImplementationTransformer
CCCDeobfPlugin (unknown)

NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-universal.jar)
codechicken.nei.asm.NEITransformer
GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.200.1062.0' Renderer: 'AMD Radeon HD 7800 Series'
Launched Version: 1.8-Forge11.14.3.1502
LWJGL: 2.9.1
OpenGL: AMD Radeon HD 7800 Series GL version 4.5.13399 Compatibility Profile Context 15.200.1062.0, ATI Technologies Inc.
GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)

**Comment by sinkillerj** [comment]
Likely uses NBT, add it to your NBT whitelist config.

**Comment by williewillus** [comment]
Might be useful for us to add it to our default one, too

**Comment by Viktorsmg** [comment]
Sorry for the delayed response,had a blackout.

flansmod:m16a4 flansmod:r870 flansmod:glock if you have the modern warfare pack.
That's just three though.There's plenty more(70-80 or so with the modern warfare,ww2 and simple parts packs).
